#!/bin/bash


####################################################
# Linking: Docker exposes connectivity information for the source container to the recipient container in two ways:
#
#   Environment variables,
#   Updating the /etc/hosts file.
#
sudo docker stop web
sudo docker stop db

# to remove
sudo docker rm -f web
sudo docker rm -f db

# start containers

# start db
sudo docker run -d --name db training/postgres


# web as app
#sudo docker run -d -P --name web --link db:db gregfelice/centos-flask python app.py

# web as shell
sudo docker run -t -i --name web --link db:db gregfelice/centos-flask /bin/bash

##########################################################################
# to connect from web to db
# psql -U postgres -h db -p 5432
##########################################################################

# on persisting data (in progress)
# https://docs.docker.com/examples/postgresql_service/
# http://www.offermann.us/2013/12/tiny-docker-pieces-loosely-joined.html
