#!/bin/bash

red='\e[0;33m'
NC='\e[0m' # No Color

function stop_and_remove_all
{
    sudo docker stop db
    sudo docker rm -f db
    sudo docker stop web
    sudo docker rm -f web
}

function build_db_container
{
    echo -e "${red}build the database${NC}"
    sudo docker build -t gregfelice/centos-postgres ./db_container
}

function build_web_container
{
    echo -e "${red}build the app${NC}"
    sudo docker build -t gregfelice/centos-flask ./app_container
}


function run_web_container_bash
{
    echo -e "${red}run the web as command line${NC}"
    sudo docker run -i -t -p 8888:5000 --name web --link db:db gregfelice/centos-flask /bin/bash
}

function run_web_container_daemon
{
    echo -e "${red}run the web as daemon${NC}"
    sudo docker run -d -p 8888:5000 --name web --link db:db gregfelice/centos-flask python app.py

    echo -e "${red}inspect the web container and it's links${NC}"
    sudo docker inspect -f "{{ .HostConfig.Links }}" web
    
    echo -e "${red}go to http://`hostname`:8888 to test.${NC}"
}

function run_db_container_daemon
{
    echo -e "${red}run the database${NC}"
    sudo docker run -d -p 7777:5432 --name db gregfelice/centos-postgres
}

######################################################################################################


stop_and_remove_all

build_db_container
run_db_container_daemon

build_web_container
# run_web_container_bash
run_web_container_daemon







