#!/bin/bash


#######################################################
# build an image from a Dockerfile
#
# this example builds a centos image that has the Flask python microframework installed.
#
#######################################################
function build_from_dockerfile
{
    sudo docker build -t $CONTAINER_NAME $DOCKERFILE_DIR
}

#######################################################
# run a docker container
#######################################################
function run_container
{
    CONTAINER="$(sudo docker $CONTAINER_INIT_ARGS)"
    echo "created container: $CONTAINER"
}

function run_container_shell
{
    sudo docker run -t -i $CONTAINER_NAME /bin/bash
}

#######################################################
# stop a docker container
#######################################################
function stop_container
{
    sudo docker stop $CONTAINER
    echo "container $CONTAINER stopped."
}

#######################################################
# see if you can hit the port via HTTP.
#######################################################
function test_container
{
    curl -i localhost:5000
}

DOCKERFILE_DIR=./db_container
CONTAINER_NAME="eg_postgresql"
PORTMAP="7777:7777"
CONTAINER_INIT_ARGS="run --rm -P --name pg_test $CONTAINER_NAME"

# run_container_shell
# build_from_dockerfile

run_container
# sleep 1
# test_container
#stop_container










