#!/bin/bash

sudo docker stop web
sudo docker rm -f web

#sudo docker run -d -P --name web --link db:db training/webapp python app.py

sudo docker run -d -P --name web --link db:db gregfelice/centos-flask python app.py

# sudo docker run -i -t -P --name web --link db:db gregfelice/centos-flask /bin/bash

# psql -U postgres -h db -p 5432
