#!/bin/bash


####################################################
# Linking: Docker exposes connectivity information for the source container to the recipient container in two ways:
#
#   Environment variables,
#   Updating the /etc/hosts file.
#

sudo docker stop web
#sudo docker stop db

# to remove
sudo docker rm -f web
#sudo docker rm -f db

# db
# sudo docker run -v="/opt/postgresdata":"/var/lib/pgsql/data"  -i -t -p 5432 gregfelice/centos-postgres:docker-database /bin/bash
#sudo docker run -v="/opt/postgresdata":"/var/lib/pgsql/data" -d --name db gregfelice/centos-postgres:docker-database

# web
#sudo docker run -d -P --name web --link db:db training/webapp python app.py
 sudo docker run -d -P --name web --link db:db gregfelice/centos-flask python app.py
#sudo docker run -d -P --name web gregfelice/centos-flask python app.py

#sudo docker run -t -i --name web --link db:db gregfelice/centos-flask /bin/bash

#sudo docker run -t -i --name web gregfelice/centos-flask /bin/bash

# to connect from web to db
# psql -U postgres -h db -p 5432

