#!/bin/bash

sudo docker stop db

sudo docker rm -f db

sudo docker run -v="/opt/postgresdata":"/var/lib/pgsql/data"  -i -t -p 5432 --name db gregfelice/centos-postgres:docker-database /bin/bash

# psql -U postgres -h db -p 5432
